<a href="https://colab.research.google.com/github/james30/Machine-Learning-With-Pytorch/blob/main/IntroToPytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TENSORS**

*   A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.

*   Similar To Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU's).

*  default data type of float32.

* More suitable for deep learning than a numpy array.







In [1]:
import torch
import numpy as np

# **LISTS**


In [2]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list


[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# **NUMPY ARRAYS**

In [3]:
np1 = np.random.rand(3,4)
np1


array([[0.97754488, 0.29434692, 0.52200801, 0.14967984],
       [0.03134137, 0.74892275, 0.45267351, 0.73667051],
       [0.54822379, 0.88802337, 0.70027445, 0.02073652]])

In [4]:
np1.dtype


dtype('float64')

# **TENSORS**

In [5]:
tensor_2d = torch.randn(3,4)
tensor_2d
#tensor_2d.dtype

tensor([[-0.4084, -1.0777, -1.5600,  0.9818],
        [ 1.3113,  0.8557, -1.2798,  0.1665],
        [-0.7633, -0.1131,  0.6914,  0.5293]])

In [6]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.9775, 0.2943, 0.5220, 0.1497],
        [0.0313, 0.7489, 0.4527, 0.7367],
        [0.5482, 0.8880, 0.7003, 0.0207]], dtype=torch.float64)

In [8]:
# create a tensor
x = torch.tensor([[1, 2], [3, 4]])

# move to GPU if available
device = 'cuda' if torch.cuda.is_available() else 'cpu'
x = x.to(device)

print('Tensor on device:', device)
print(x)

Tensor on device: cpu
tensor([[1, 2],
        [3, 4]])
